language: haskell
install:
  - cabal install cabal-dev
  # - cd engine && cabal install --only-dependencies --enable-tests
script:
  # - cabal configure && cabal build && ./dist/build/shakefile/shakefile test
  - ./stir update && ./stir test
env: CC=clang TOOLCHAIN_VARIANT=clang
