language: haskell
install:
  # - cabal install hsc2hs cabal-dev
  # - cd engine && cabal install --only-dependencies --enable-tests
  - cabal install split
script:
  # - cabal configure && cabal build && ./dist/build/shakefile/shakefile test
  - cd engine && ./stir update --force-reinstalls && ./stir test
env: CC=clang TOOLCHAIN_VARIANT=clang
